### PR TITLE
(#699) npm install step is missing from the manual

### PR DESCRIPTION
**Pull request by gnurag**
- Added npm install command under Installing from source section of the manual (#699)
- Updated GNU GPL license name to use its correct form

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks, a few points:
- Please add npm to the dependencies towards the top of the section
- `rake webpack:compile` is also required prior to starting the Rails server
- ditto in the upgrade section (3.6), suggest running `npm up` or similar, plus webpack:compile

**Comment by gnurag** [comment]
Hi @domcleal, the upgrade section does not have a separate section for source-only installations so haven't tried that yet.

**Review by domcleal — CHANGES_REQUESTED** [review]
The upgrade section has "Step 2 (D) - git checkouts only" which is for source installations, the step(s) can go in there.

There also seem to be unrelated commits that are already on `gh-pages` in your branch, please remove them.

**Comment by gnurag** [comment]
Closing this PR and opening a fresh clean PR.

**Pull request closed without merging**
