### PR TITLE
Dropping virsh, added libvirt providers

### PR DESCRIPTION
**Pull request by lzap**
Reflects changes in

https://github.com/theforeman/smart-proxy/commit/6798dc589b83eb601a135f914db5ec2308c492e1

puppet changes in

https://github.com/theforeman/puppet-foreman_proxy/pull/240

### CODE REVIEW

**Comment by domcleal** [comment]
The change was not shipped in Foreman 1.11, so the 1.11 docs shouldn't be changed.  It's already on the 1.12 checklist at #555, please re-submit a PR then.

Any changes to the installer docs _must_ be made in the installer Puppet modules themselves, the docs are autogenerated.

**Comment by lzap** [comment]
I rebased onto 1.12.

**Comment by lzap** [comment]
Hmmm I click Reopen but the button is now gray. Looks like stuck (no merge button). Shall I reopen new one, or can you merge manually?

**Comment by domcleal** [comment]
Please just open a new PR.

**Pull request closed without merging**
