### PR TITLE
switch to kramdown for markdown processing

### LINKED ISSUE #542: gh-pages deprecates rdiscount markdown
Per GitHub:

You are currently using the 'rdiscount' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

### PR DESCRIPTION
**Pull request by mmoll**
closes GH-542

### CODE REVIEW

**Comment by mmoll** [comment]
seems like I forgot to check also the blog ports, there are some issues with them...

**Comment by mmoll** [comment]
there we go...

**Comment by domcleal** [comment]
1. 1.10 manual, section 4.1.1: LDAP authentication heading isn't taking effect, missing a line break between headings.
2. Ditto in lots of other sections, search for `###` in `_site/`
3. Ditto in /2015/04/foreman-community-newsletter-april-2015.html (1.8.0/1.7.5 heading)
4. Section 4.3.9 (TFTP) in most versions, `<destination>` is used inside `<pre>` tags and needs changing.

**Comment by mmoll** [comment]
should all be fixed now

**Comment by domcleal** [comment]
Thanks @mmoll!

**Pull request merged**
