### PR TITLE
Make libvirt/tftp instructions clearer

### PR DESCRIPTION
**Pull request by jbrouault**

### CODE REVIEW

**Comment by stbenjam** [comment]
Thanks @jbrouault!

**Comment by lzap** [comment]
Well the libvirt provider is meant mainly for development setups, therefore in development setup there is no foreman-proxy user usually. The instructions were right, I believe. But I guess this will not hurt too.

**Comment by lzap** [comment]
I mean what I usually do is I run both foreman and proxy under my own ("lzap") UNIX account. Thanks for contribution.

**Comment by jbrouault** [comment]
Well, I stumbled upon problems while trying a "real" installation of foreman with the libvirt provider because I didn't want BIND and ISC DHCP. I guess the clarification won't hurt anyone ;)
By the way, will the libvirt provider remain "not recommended for production" or is this going to change in the near future ?

**Comment by stbenjam** [comment]
Libvirt compute resource should be fine.. I think it's only the virsh provider to avoid in production, which limits you to just the one host, right @lzap?

Anyway, I merged the change since I figured the manual should target the released version, and if you're running from git then you should know what user you are (I hope) :-)

**Comment by lzap** [comment]
It's fine, thanks. I just commented because it might be misleading for devs who are doing the first development setup (there will not be any foreman-proxy user account usually).

Well, we do not recommend it for because nobody tried this yet in production. It might work just fine, but remember there is no DNS PTR records support (no support in virsh XML I believe). And it is good point by @stbenjam that you can have only one hypervisor in the virtual network - this is also limiting.

If you are fine with one network one hypervisor for you production setup, feel free to test this for some months and then get back to us and report your success story. We will be happy to update the docs :-)

**Pull request merged**
