### PR TITLE
Rework salt documentation

### PR DESCRIPTION
**Pull request by maximiliankolb**
First draft on reworking the Salt Plugin docs.

Goal: Move the remaining parts to [Using Salt for Configuration Management](https://docs.theforeman.org/nightly/Managing_Hosts/index-foreman-el.html#using-salt-for-configuration-management_managing-hosts) in the Foreman documentation.

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Ready for review @bastian-src

**Comment by nadjaheitmann** [comment]
What about release notes and compatibility matrix?

**Comment by maximiliankolb** [comment]
I am not aware of any release notes & the compatibility matrix is part of the [foreman_salt Readme](https://github.com/ATIX-AG/foreman_salt#compatibility), albeit without smart proxy plugin. 

For version 13, the release notes are still there.

**Comment by nadjaheitmann** [comment]
> I am not aware of any release notes

https://theforeman.org/plugins/foreman_salt/13.0/index.html#1.1ReleaseNotes --> But I guess it is fine if we keep release notes as part of Foreman packaging. I have not seen many release notes for other plugins inside the documentation (correct me if I am wrong). 

I think it is okay to have the compatibility matrix on the readme page, only. One place to maintain is enough IMHO.

**Comment by maximiliankolb** [comment]
@bastian-src, @nadjaheitmann, and I had a quick discussion and think this is ok as is for now. This is ideally merged after https://github.com/theforeman/foreman/pull/8489.

**Comment by maximiliankolb** [comment]
Added a link to the Foreman docs and rebased to `gh-pages`.

Ready to be merged.

**Comment by nadjaheitmann** [comment]
Let's wait until foreman_salt 14.0 is released, then :)

**Review by melcorr — APPROVED** [review]

**Comment by nadjaheitmann** [comment]
Thanks for approving @melcorr We still need to wait as Salt 14.0 has not been merged to forman-packaging, yet. There are still some dependencies that need to be resolved, e.g. https://github.com/theforeman/foreman/pull/8489

**Comment by lzap** [comment]
The patch was merged, where are we? :)

**Comment by maximiliankolb** [comment]
Rebased & ready to merge.

**Comment by maximiliankolb** [comment]
Rebased to master. Ready to merge @melcorr

**Comment by melcorr** [comment]
Thank you!

**Pull request merged**
