### PR TITLE
Remove Chef chapter

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by dLobatog** [comment]
Can we simply the section to point to the Chef manual? I ask because the Documentation buttons (haven't checked) rely on the numbers, and that might fail.

**Comment by ares** [comment]
@domcleal suggested renumbering which also makes more sense to me, chef is no longer part of Foreman core in any way. But if you insist I can just add link there :-)

**Comment by domcleal** [comment]
Hm, good point @eLobato.  We have links to the realm section in Foreman, so we should only change numbering in the 1.9 manual I suppose...

**Comment by dLobatog** [comment]
Sounds fair, @ares mind making the changes on 1.9, and check if any documentation button would be affected? (I think only the one that links to Realms is) 
Should be good to go after that as far as I can see.

**Comment by ares** [comment]
So I changed the chapter just to link (without renumbering). When we have 1.9 manual, this can be removed and links changed accordingly.

**Comment by domcleal** [comment]
Thanks @ares, I'll put it on the 1.9 list.  Sorry for the back and forth.

**Pull request merged**
