### PR TITLE
blog post

### PR DESCRIPTION
**Pull request by MariSvirik**
post about a new search design @melcorr

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
We typically use https://community.theforeman.org/c/development/rfcs/18 for open discussion. Perhaps you can start a post there and link to it?

**Comment by melcorr** [comment]
> We typically use https://community.theforeman.org/c/development/rfcs/18 for open discussion. Perhaps you can start a post there and link to it?

Hey @ekohl do you mean that if we publish the blog, create an RFC and link to this blog post? 
If so, think that would be great.

**Comment by melcorr** [comment]
ping @ekohl did I understand you correctly? 
Do you have any objection to my proposal? I don't want to merge without your ack, as previously discussed.
I would love this to come in on folks' RSS feed so they can see what UX proposals are being made.

**Comment by melcorr** [comment]
@MariSvirik Ewoud is on PTO, so if you could update the date to today, I will publish this blog. 
It takes a bit of time to build, when built, I would ask that you open an RFC in our community to solicit further feedback. 
I am sorry for the delay with this.

**Comment by ekohl** [comment]
For the record: RFCs should be self descriptive. So the RFC should **not** refer to the blog post for details. It can at most refer to it as "in blog X attention was requested".  If I'm honest, I'm not too happy about moving the RFC process to the blog. We've already struggled enough (and still do) with getting attention to the RFC category. This only further dilutes the focus.

IMHO a blog at most should be:
* A short summary
* A link to the RFC for technical details
* A link to the questionnaire

However, I'll also add that I think Google is user hostile. When I was an upstream user I always refused to use it due to its privacy policy (and despise that it's so commonly used within Red Hat). Discourse has capabilities for polls and has room for discussion. IMHO that should be preferred.

**Comment by MariSvirik** [comment]
@ekohl here is also RFC https://community.theforeman.org/t/rfc-search-input-design-proposal/24895

**Pull request merged**
