### PR TITLE
Adding nice table for 1.3 installer options

### PR DESCRIPTION
**Pull request by lzap**
:)

### CODE REVIEW

**Comment by domcleal** [comment]
Perhaps wait for http://projects.theforeman.org/issues/3337 and we can then just document the useful ones?

**Comment by lzap** [comment]
Hmmm, if you say that. But note we have no single page on the internet
with all the parameters. Only the --help screen.

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
Yeah, I agree it'd be good.  It just looks long (at least in Markdown) :)

I wonder when @ares might be done...?

**Comment by lzap** [comment]
Well we have MD table output, but it is quite huge in size (lots of

## columns). This looked the best.

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
Ah yes, it doesn't look nearly so bad when you view the rendered version.  I don't mind doing it as-is, but would suggest once 3337's done that we only publish the useful ones.

**Comment by lzap** [comment]
> Ah yes, it doesn't look nearly so bad when you view.

Oh yes, it looks gorgeous.

> I don't mind doing it as-is.

Thank you! :-)

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
Okay, merged as f9c37f40ca, thanks!

**Pull request closed without merging**
