### PR TITLE
Instruct to stop Katello before yum update

### PR DESCRIPTION
**Pull request by akofink**
Step 17 in the [downstream docs](https://access.redhat.com/documentation/en-us/red_hat_satellite/6.2/html/installation_guide/upgrading_satellite_server_and_capsule_server).

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]
LGTM

**Comment by mmoll** [comment]
merged, thanks @akofink!

**Comment by ekohl** [comment]
Would it make sense to do this in the 3.4 docs as well?

**Comment by akofink** [comment]
I do believe this applies to 3.4. @ehelms?

**Comment by ehelms** [comment]
It should but we haven't tested it. So I am tempted to not put it in the instructions.

**Pull request merged**
