### PR TITLE
Change to GA version for Katello 3.15.0

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]

**Comment by jturel** [comment]
Also need to update the latest version here: https://github.com/theforeman/theforeman.org/blob/8bfa5185dbb7034da5049682c686ad1f459c87e9/_config.yml#L112

This probably warrants an update to the procedure in tool_belt

**Comment by jjeffers** [comment]
> theforeman.org/_config.yml

I always forget at last a couple of these.

**Comment by jturel** [comment]
Looks good, let me know when you are pressing the button on the GA announcement and I'll merge this in.

**Review by jturel — APPROVED** [review]
ACK

**Review by chris1984 — APPROVED** [review]

**Pull request merged**
