### PR TITLE
Add foreman-announce list

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by lzap** [comment]
Oh we do have announce list? :-D +1

**Comment by domcleal** [comment]
Did you miss the announcement? :)

**Comment by lzap** [comment]
Tested, it works.

**Comment by domcleal** [comment]
Thanks @lzap.  I've added you to the website team, please go ahead and push if you're happy with it :)

On the website project we're not fussy about how you merge.  We use a variety of the GitHub merge button, cherry picking and merge --ff.  It's up to you.

**Comment by lzap** [comment]
Merged as 7cdc2f5 thank you.

**Pull request merged**
