### PR TITLE
Add headline features for 1.11

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by mmoll** [comment]
:+1: maybe the new Patternfly UI is also worth mentioning here?

**Comment by domcleal** [comment]
Perhaps, I was thinking about it but I don't think there's much to say about it.

**Comment by mmoll** [comment]
That's also correct... merged, thanks @domcleal!

**Comment by GregSutcliffe** [comment]
I'll get clips done for those next week

**Pull request merged**
