### PR TITLE
Add 'System testing: Puppet management' project

### PR DESCRIPTION
**Pull request by domcleal**
- refactor

### CODE REVIEW

**Comment by domcleal** [comment]
Don't merge yet, some formatting's wonky...  edit: fixed

**Comment by GregSutcliffe** [comment]
:+1: I'm also happy to be a possible mentor for that if you want to update

**Comment by domcleal** [comment]
@GregSutcliffe updated, thanks

**Comment by GregSutcliffe** [comment]
Merged, thanks!

**Pull request closed without merging**
