### PR TITLE
Branch manual for Foreman 3.0

### PR DESCRIPTION
**Pull request by upadhyeammit**

### CODE REVIEW

**Comment by melcorr** [comment]
Will there be a 3.0 manual here if we complete https://projects.theforeman.org/issues/33169 as planned?

**Comment by tbrisker** [comment]
Could you include #1865 in this pr so we don't lose that warning?

**Comment by tbrisker** [comment]
@upadhyeammit please rebase

**Comment by upadhyeammit** [comment]
> Will there be a 3.0 manual here if we complete https://projects.theforeman.org/issues/33169 as planned?



> @upadhyeammit please rebase

Rebased and moved upgrade warning to 3.0 release notes.

**Comment by upadhyeammit** [comment]
> Will there be a 3.0 manual here if we complete https://projects.theforeman.org/issues/33169 as planned?

I dont think we should also have it here. I thought not to immediately stop updating documentation of existing site to not lose some bits in the process of change.

**Review by tbrisker — APPROVED** [review]
Thanks, there's still a lot more needed in the headline features and upgrade warnings, but let's get it in an update later.

**Pull request merged**
