### PR TITLE
Bump 3.17 version to GA

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@jturel for when 3.17.0 gem gets pushed

**Comment by jturel** [comment]
also need to set 3.17 as latest version : https://github.com/theforeman/theforeman.org/blob/256f7da0f1a1ee04312e4c44b7083e60d0bb9e70/_config.yml#L114

**Comment by chris1984** [comment]
@jturel nice catch, updated.

**Review by jturel — APPROVED** [review]

**Comment by chris1984** [comment]
@jturel finished testing 3.17.0 and everything looks good. Can this get a merge and I will make the announcement.

**Pull request merged**
