### PR TITLE
Show page title correctly everywhere

### PR DESCRIPTION
**Pull request by stbenjam**
@GregSutcliffe's PR made me realize this is missing a lot of places like the manuals.  This probably looks better on search results:

Foreman 1.9 Manual: **Foreman :: Manual :: Foreman 1.9 Manual**

REX Manual: **Foreman :: Plugin Manuals :: Foreman Remote Execution 0.0 Manual**

### CODE REVIEW

**Comment by domcleal** [comment]
I like that the {{page.title}} is used now, looking through what's set it makes a lot more sense to use it where possible.  I don't think though that page.pagename adds much on most pages since it's normally only set in the layout (with the single exception of blog/index.html).

The duplication of "Manual(s)" in the two examples you give suggests to me that it should be removed, making the relevant bit come earlier in the page title.

How about using "Foreman :: {{page.title}}" even if both pagename and title are set, but just "Foreman :: {{page.pagename}}" when only pagename is set?  Either that or remove pagename from the layouts where title is set on all the pages using the layout (e.g. plugin, manual, contribute, support).

**Comment by stbenjam** [comment]
I had both because it kind of gives it a hierarchy appearance, maybe it'd be better without the Manual on the last part, so it's like this: 

**Foreman :: Manual :: Foreman 1.9**

or

**Foreman :: Plugin Manual :: Foreman Remote Execution 0.0**

Or it might just be easier to remove the `page.pagename` from everything and just require everything to have a `page.title`?

**Comment by domcleal** [comment]
Yeah, I see what you're trying to do.  I'm just concious about the need to keep the title snappy for when it appears in search results, so reduce length and duplication where possible.  I don't know whether "Foreman :: Manual :: Foreman 1.9" or "Foreman :: Foreman 1.9 manual" is better... or even "Foreman 1.9 manual", up to you!

I think we can safely get rid of pagename from everything and move a couple of them into page.title if not already there if you like.

**Comment by GregSutcliffe** [comment]
Late to the party, but +1 for page.title everywhere, simplicity FTW.

For the manual, I agree with removing duplication, including the word Foreman - so "Foreman 1.9 Manual" or "Foreman :: Manual :: 1.9" would work for me. $0.02, etc ;)

**Comment by GregSutcliffe** [comment]
ping @stbenjam - what's the status here? Are you planning to update to one of your earlier suggestions?

**Comment by stbenjam** [comment]
No longer needed, site is very different than when I opened this PR.

**Pull request closed without merging**
