### PR TITLE
Removed TEMPLATE_CONTEXT from logs

### PR DESCRIPTION
**Pull request by lzap**
This is for https://github.com/theforeman/foreman/pull/5683

### CODE REVIEW

**Comment by tbrisker** [comment]
Thanks @lzap, is this the only change needed in the manual regarding the rendering change?

**Comment by tbrisker** [comment]
@timogoebel same question :wink:

**Comment by timogoebel** [comment]
Good catch.

I think this should be all as we mostly did a refactoring. What did change was, that you cannot use the template macros defined in https://github.com/theforeman/foreman/blob/develop/lib/foreman/renderer/scope/variables/base.rb in partition tables anymore. But this should not hurt.

**Comment by lzap** [comment]
Yeah this field is not a big deal.

**Review by tbrisker — APPROVED** [review]
Thanks @lzap and @timogoebel !

**Pull request merged**
