### PR TITLE
Add preview clips for release highlights

### PR DESCRIPTION
**Pull request by GregSutcliffe**
Videos are currently unlisted but links should work - will make them public once we're done. I think the audio may still need tweaking on a couple, but I have the raw files so it can be re-rendered easily enough. Comments welcome.

### CODE REVIEW

**Comment by domcleal** [comment]
The audio on the middle two videos (smart proxies, bulk actions) is somewhat lower than the other two (test buttons is higher than inline params, but both are OK), could you increase those?

Otherwise fine, thanks.

**Comment by ohadlevy** [comment]
I agree on the audio as well, i had to bump volume across the videos multiple time.
I also found it odd that your select/dropdowns have  a black background, making it odd looking.

and in general, I would recommend to have more content in your foreman instance, as one host demo is not very appealing.

thanks!

**Comment by GregSutcliffe** [comment]
Thanks guys, I have no idea why my mic is so variable (these were all recorded on the same day...). On the plus side, I've now learned how to use ffmpeg to normalise to a set dB level, so once I re-upload they should be consistent from now on.

Thanks for the catch on the weird black menus, I hadn't really noticed. GTK is doing some weird interaction with Firefox lately - if I get chance I'll re-record that segment.

**Comment by GregSutcliffe** [comment]
Ok, all videos re-uploaded and URLs changed here. I've normalised to 0dB so it should be _much_ louder now. I did also manage to fix the GTK issue, so the smart-proxy vid is a new recording without the black menus.

**Comment by domcleal** [comment]
Merged, thanks @GregSutcliffe.

**Pull request merged**
