### PR TITLE
Fix URL path to foreman-release.rpm in 3.3 Smart Proxy upgrade process

### PR DESCRIPTION
**Pull request by jbnance**
http://projects.theforeman.org/issues/19671

### CODE REVIEW

**Comment by lzap** [comment]
Thank you!

**Comment by lzap** [comment]
Ah merged too quickly, we still have couple of others, would you mind fixing them as well? Very appreciated thanks!

```
3.3/upgrade/smart_proxy.md
28:  yum update -y http://yum.theforeman.org/{{ page.foreman_version }}/el7/x86_64/foreman-release.rpm

nightly/upgrade/index.md
45:  yum update -y http://yum.theforeman.org/{{ page.foreman_version }}/el7/x86_64/foreman-release.rpm

nightly/upgrade/smart_proxy.md
28:  yum update -y http://yum.theforeman.org/{{ page.foreman_version }}/el7/x86_64/foreman-release.rpm

3.4/upgrade/index.md
42:  yum update -y http://yum.theforeman.org/{{ page.foreman_version }}/el7/x86_64/foreman-release.rpm

3.4/upgrade/smart_proxy.md
28:  yum update -y http://yum.theforeman.org/{{ page.foreman_version }}/el7/x86_64/foreman-release.rpm

2.4/upgrade/capsule.md
30:  yum update -y http://yum.theforeman.org/{{ page.foreman_version }}/el6/x86_64/foreman-release.rpm
37:  yum update -y http://yum.theforeman.org/{{ page.foreman_version }}/el7/x86_64/foreman-release.rpm

2.4/installation/index.md
87:yum -y localinstall http://yum.theforeman.org/{{ page.foreman_version }}/el6/x86_64/foreman-release.rpm
107:yum -y localinstall http://yum.theforeman.org/{{ page.foreman_version }}/el7/x86_64/foreman-release.rpm

3.0/upgrade/capsule.md
41:  yum update -y http://yum.theforeman.org/{{ page.foreman_version }}/el6/x86_64/foreman-release.rpm
48:  yum update -y http://yum.theforeman.org/{{ page.foreman_version }}/el7/x86_64/foreman-release.rpm
```

**Comment by jbnance** [comment]
I'm on it.

**Comment by jbnance** [comment]
New PR created: https://github.com/theforeman/theforeman.org/pull/880
Issue updated as well: http://projects.theforeman.org/issues/19671

**Pull request merged**
