### PR TITLE
Sunsetting foreman_cockpit because functionality being integrated in remote execution

### PR DESCRIPTION
**Pull request by dgoetz**
According to https://community.theforeman.org/t/sunsetting-foreman-cockpit/14787

### CODE REVIEW

**Comment by ekohl** [comment]
I wonder about this. We never really had a policy around removing things. Perhaps we should add banners that it's outdated?

**Comment by dgoetz** [comment]
It is actually broken because there was no release to make it compatible again and it can also break other plugins (because of alias_method_chain). This is why I would completely remove it. 

Functionality will return within REX, so we could also replace with a banner and link to REX documentation when it is added.

**Comment by ekohl** [comment]
I was thinking that there still might be links to it. Displaying a big banner that it's broken since Foreman 1.x will inform them they shouldn't even try, even if we did ship it for some releases in a broken state.

**Comment by tbrisker** [comment]
i tend to agree with ekohl, some people might still be using it on older versions. Would also be good to mention in the upgrade notes for 1.24.

**Review by tbrisker — APPROVED** [review]
thanks @dgoetz !

**Comment by dgoetz** [comment]
You were faster than I while waiting for the tests to pass. I am not totally happy with it, because documentation for the new feature in REX is missing. If I remember then, I will add a more details to the banner when documentation is added.

**Comment by tbrisker** [comment]
Actually, thinking about it again, can you remove the link to the plugin from the plugins list and also add the same disclaimer on the top of the 1.0 manual?

**Comment by dgoetz** [comment]
I removed the link and added the disclaimer also to the versioned site. I recognized the noindex option for robots which I added to both sites, so they are hopefully not showing up when searching and instead the future documentation for Cockpit in REX will be found.

**Review by tbrisker — APPROVED** [review]
Thanks @dgoetz !

**Pull request merged**
