### PR TITLE
Refs #31641 - Add Deprecation warnings for katello-agent

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@jturel how does this look?

**Comment by jturel** [comment]
@chris1984 looks good! can you port it back to maybe .. 3.16 or so? Also please add similar messaging to release notes back thru 3.16 (may be mentions that need updating or adding)

**Comment by chris1984** [comment]
@jturel updated

**Review by jturel — APPROVED** [review]
ACK!

**Pull request merged**
