### PR TITLE
Add a link to the developer handbook

### PR DESCRIPTION
**Pull request by ekohl**
Closes GH-806

### CODE REVIEW

**Comment by ekohl** [comment]
I should note that I haven't checked how this renders because I don't know how.

**Comment by mmoll** [comment]
I think the change itself is fine, but maybe we should switch to a 5x2 layout then?

**Comment by ekohl** [comment]
I'm not sure, maybe 4x3 (with 2 empty spots)?
screen shot 2017-02-03 at 14 09 26

**Comment by mmoll** [comment]
@ekohl I'm fine with 4x3 👍

**Comment by ekohl** [comment]
Updated

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
