### PR TITLE
Release 1.15.0

### PR DESCRIPTION
**Pull request by GregSutcliffe**
Carbon-copy of 018d65c85ca23c5f2bc83bb15a485c60eb715d94 - hope I got it all.

### CODE REVIEW

**Comment by evgeni** [comment]
ACK :+1:

**Comment by evgeni** [comment]
(this obsoletes https://github.com/theforeman/theforeman.org/pull/867)

**Comment by GregSutcliffe** [comment]
> (this obsoletes #867)

Yeah, with @dLobatog on leave for a bit I figured it was quicker to just do a new one.

**Comment by gnurag** [comment]
this string? (*hopes it isn't autogenerated one)
`_layouts/quickstart.html:3:latestversion: "1.14"`

**Comment by GregSutcliffe** [comment]
Good catch @gnurag - fixed

**Pull request merged**
