### PR TITLE
Clarify EL6 removal for Foreman 1.13 in release notes

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ohadlevy** [comment]
please do not merge this until a final decision is made on foreman-dev thread.

**Comment by dLobatog** [comment]
https://github.com/theforeman/foreman-packaging/commit/9e2e51d2ba4433c412dca31a22ff75568ec4b512 was pushed already though. 
It sat open for nearly a month without comments https://github.com/theforeman/foreman-packaging/pull/1201

**Comment by ohadlevy** [comment]
Anything can be reverted...

**Comment by dLobatog** [comment]
The more we delay reverting that commit the worse it gets though, as the repo has changes but isn't taking into account el6.

**Comment by mmoll** [comment]
merged, as 1.13 does not support EL6 now.

**Pull request merged**
