### PR TITLE
Fix Debian family upgrade instructions w.r.t. stopping/starting Apache.

### PR DESCRIPTION
**Pull request by dhs-rec**
Since nobody seems to react on my FlySpray reports, I fixed the documentation myself. Looks like nightly was already fixed, but past releases were not.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Thanks!

> Since nobody seems to react on my FlySpray reports

What is FlySpray? Never heard of it.

**Comment by dhs-rec** [comment]
Meant the ticketing system used by the project: https://projects.theforeman.org/projects/foreman-website/issues?set_filter=1&tracker_id=1. Thought it was [Flyspray](https://www.flyspray.org/).

**Comment by dhs-rec** [comment]
Thanks for the quick merging.

**Comment by ekohl** [comment]
Ah. We've had discussions about Redmine VS GH issues. I must admit I haven't looked at Redmine for a while, but recently took over release management. I'll think about this.

**Pull request merged**
