### PR TITLE
1.2.0-RC3 release notes

### PR DESCRIPTION
**Pull request by domcleal**
Please don't merge until we're ready to push RC3, thanks.

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Looks great! Maybe add a line re the db_password issue in the installer as we were just discussing?

**Comment by domcleal** [comment]
Thanks, will add that to my e-mail (keeping known issues in there instead).

**Comment by GregSutcliffe** [comment]
Fine, :+1: then

**Comment by domcleal** [comment]
Merged as 1e52be6.

**Pull request closed without merging**
