### PR TITLE
add upgrade warning about chef and abrt

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Should this reflect that abrt was already gone from packaging?

**Comment by evgeni** [comment]
> Should this reflect that abrt was already gone from packaging?

I wouldn't know how to phrase it without making it overly complicated and less understandable.

If you have a suggestion, sure.

**Comment by ekohl** [comment]
I think we can drop abrt since it was already uninstallable. The installer didn't expose it and there was no package. I even documented its removal in `_includes/manuals/1.22/1.2_release_notes.md` already (and made https://projects.theforeman.org/issues/26665). Keeping it in puppet-foreman(_proxy) was an oversight.

**Comment by evgeni** [comment]
Fair.

**Review by ekohl — APPROVED** [review]

**Pull request merged**
