### PR TITLE
Added monitoring and telemetry blog post

### PR DESCRIPTION
**Pull request by lzap**
This is HUGE article. Reviewers *please* do not comment and fix my grammar directly using github editor and add new commit with changes. This will contain lots of bad English.

I can't get the page genreated tho, I run jekyll and nothing appears in my local site. Looks like jekyll is ignoring the file for some reason.

### CODE REVIEW

**Comment by ares** [comment]
could some any native speaker take a look? I think it does not require any tech review :-) perhaps @GregSutcliffe

**Comment by GregSutcliffe** [comment]
Just seen this, sorry - will add to my TODO. @lzap, your request is unclear - you *want* people to push new commits directly, or you *don't want* them to?

Context: `Reviewers please do not comment and fix my grammar directly using github editor and add new commit with changes` - the `and` here makes it into a single logical block but the negative is poorly specified: you can interpret this as either `please (not comment) && (push direct)` or `please not (comment && push direct)`, both are valid :P  \</english lesson\>

**Comment by ares** [comment]
As a person who speaks czenglish fluently, I understood that he prefers you to directly fix typos instead of adding comments. That will be more efficient since it's along text. This way you fix it as you read it.

**Comment by lzap** [comment]
Lemme try again: Reviewers do use github editor directly instead commenting. Thanks.

**Comment by GregSutcliffe** [comment]
Merged as 260c4c371 with just a few minor edits - ty @lzap!

**Pull request closed without merging**
