### PR TITLE
Add noindex meta HTML tags to old pages

### PR DESCRIPTION
**Pull request by lzap**
SSIA @mmoll

### CODE REVIEW

**Comment by lzap** [comment]
@ehelms are you fine with this for Katello? I should probably also ping all plugin authors, maybe just the biggest plugins: @iNecas @xprazak2

**Review by iNecas — APPROVED** [review]
Works for me

**Comment by xprazak2** [comment]
Works for me as well.

**Review by ehelms — APPROVED** [review]

**Comment by mmoll** [comment]
merged, díky @lzap

**Comment by lzap** [comment]
Thanks all, please help me to take care when reviewing manual version bumps and ask authors to update this meta tag. Specifically Katello is a bit more complicated as it's the only multi-page manual, plugins are pretty easy.

**Pull request merged**
