### PR TITLE
Update the API docs from the 1.2-stable branch

### PR DESCRIPTION
**Pull request by skottler**
@inecas is it new for the `apidoc-onepage.html` and `apidoc-plain.html` to no longer get generated?

### CODE REVIEW

**Comment by domcleal** [comment]
What happened to the examples?

**Comment by skottler** [comment]
@domcleal not sure why they didn't get generated properly. Any idea @inecas?

**Comment by iNecas** [comment]
I could not reproduce: having fresh installation on ruby1.9.3, removed Gemfile.lock, bundle install, rake apipie:static gave me all the apidoc files, including the examples.

**Comment by iNecas** [comment]
@skottler have you by any chance update the doc/apipie_examples.yml by running tests with APIPIE_RECORD=examples?

**Comment by skottler** [comment]
@iNecas nope, it's a completely fresh instance with its own DB and no special options.

**Comment by iNecas** [comment]
@skottler what db driver to use? (it's unlikely to have any influence, but I'm quite desperate:)

**Comment by domcleal** [comment]
Replaced by #127.

**Pull request closed without merging**
