### PR TITLE
updating URL for foreman_chef plugin documentation

### PR DESCRIPTION
**Pull request by kamihacker**
documentation points to version 0.1 which is not the latest version (0.2) at the moment

### CODE REVIEW

**Comment by stbenjam** [comment]
What do you think about just linking to the landing page? http://theforeman.org/plugins/foreman_chef/

**Comment by kamihacker** [comment]
agreed, I didn't know that would be a valid URL, nor thought about it

**Comment by dLobatog** [comment]
I'll change it on merge. Thanks for pointing this out!

**Comment by dLobatog** [comment]
Merged as 552abd21487f324e853834a81f248a0526b372a2, thanks @kamihacker !

**Pull request closed without merging**
