### PR TITLE
Noted AD cert format for trusted CAs

### PR DESCRIPTION
**Pull request by swizzley**
tested in 1.7

### CODE REVIEW

**Comment by swizzley** [comment]
added to 1.8 docs too from

**Comment by swizzley** [comment]
https://github.com/theforeman/theforeman.org/pull/361

**Comment by mmoll** [comment]
Please squash the four commits into one, see https://help.github.com/articles/about-git-rebase/
Also, I _think_ `Base64` is the correct notation.

**Comment by swizzley** [comment]
Active Directory labels it Base-64, since that's were it will be exported that's why I used that notation

**Comment by mmoll** [comment]
thanks @swizzley :icecream:

**Comment by swizzley** [comment]
wrote a patch:
https://forge.puppetlabs.com/swizzley88/theforeman_174_ad_ldap_patch/readme

**Pull request merged**
