### PR TITLE
Chapter 4.2

### PR DESCRIPTION
**Pull request by GregSutcliffe**
Needs a preview as the highlight sections don't work locally. Probably need to convert some bold face to chapter hyperlinks too

### CODE REVIEW

**Comment by ohadlevy** [comment]
Any chance to update the screenshoots?

**Comment by GregSutcliffe** [comment]
Potentially. I want to get chapters 4.4 and 5 written next though, as they're missing entirely.

**Comment by skottler** [comment]
@ohadlevy can we merge this as is and then update the screenshots?

**Comment by ohadlevy** [comment]
Sure

**Comment by skottler** [comment]
Okay great. I will work on the new screenshots now and then submit updates.

**Comment by GregSutcliffe** [comment]
@skottler added a start on chapter 4.4. Needs more work, but at least people have something to read

**Pull request merged**
