### PR TITLE
Add 3.11.4 release notes

### PR DESCRIPTION
**Pull request by ColeHiggins2**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Could you sync this up to https://github.com/theforeman/foreman-documentation/pull/3392?

**Comment by ColeHiggins2** [comment]
> Could you sync this up to [theforeman/foreman-documentation#3392](https://github.com/theforeman/foreman-documentation/pull/3392)?

@ekohl Could you clarify what you mean by sync?

**Comment by ekohl** [comment]
Make sure they have the same changes.

**Comment by ColeHiggins2** [comment]
@ekohl Looks the same to me. Only thing that is different is the Debain 12 part. Want me to add that?

**Comment by ekohl** [comment]
I don't see an entry for 3.11.3 and indeed Debian is missing

**Review by ekohl — APPROVED** [review]

**Pull request merged**
