### PR TITLE
blog: July newsletter

### PR DESCRIPTION
**Pull request by GregSutcliffe**
Ugh, lack of sleep, totally forgot about this last week ...

### CODE REVIEW

**Comment by ohadlevy** [comment]
:+1:

**Comment by GregSutcliffe** [comment]
Ugh, have to run for childcare stuff - does anyone want to add these photos?

* https://twitter.com/netways/status/890613083399376896
* https://twitter.com/netways/status/890523883580915712
* https://twitter.com/KrisBuytaert/status/887376588475641856

Will try to check back later, either way ;)

**Comment by GregSutcliffe** [comment]
Links to Twitter added, the photos break up the flow too much otherwise.... (plus those accounts deserve the traffic :P)

**Comment by GregSutcliffe** [comment]
Links to Twitter added, the photos break up the flow too much otherwise.... (plus those accounts deserve the traffic :P)

**Pull request merged**
