### PR TITLE
Add infrastructure sponsors

### PR DESCRIPTION
**Pull request by domcleal**
CC @paradoxbound, @bgupta, @joshuabaird - are you happy with a) being mentioned and b) what I've written?  Also happy to add logos instead of text if you have them available.

And thanks :)

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Looks good to me :+1:

**Comment by joshuabaird** [comment]
Yessir, looks good to me.

**Comment by paradoxbound** [comment]
The Positive people are happy +1

**Comment by domcleal** [comment]
Thanks folks, merged!

**Pull request closed without merging**
