### PR TITLE
Added Google Custom Search

### PR DESCRIPTION
**Pull request by lzap**
Experimental - this is how it looks like.

And this is how results look like:

It is possible to search in Bugzilla too, not sure if this is relevant here.

WARNING: Do not merge because the results can contain ADs and the money would
go on my account. We want this to go to Foreman account. So if you like this,
Ohad please generate new GCE (I went with all defaults) and send me the ID.

### CODE REVIEW

**Comment by lzap** [comment]
I added Red Hat Satellite bugzilla search as well which might be handy (some reports are there but missing upstream). Unfortunately we need two search boxes - I am not able to combine the two results with "keyword search: Red Hat Satellite 6" which is needed to filter out non-satellite bugs from bugzilla.

There is one way - if we modify our RedMine to include this text, then we can combine those into one search. That would be great IMHO. What you think?

**Comment by lzap** [comment]
Ok the bugzilla search does not work well, it's all or nothing. Although I am able to add "Red Hat Satellite 6" keyword for the CSE so it returns more relevant results, it also shows results which are not relevant. Which might be maybe good...

**Comment by domcleal** [comment]
Thanks @lzap!

**Comment by lzap** [comment]
@domcleal @ohadlevy I've doublechecked and this GCE is not linked with any AdSense account.

**Comment by domcleal** [comment]
@lzap phew.  sorry, I missed the do not merge in the middle of the thread :)

**Comment by lzap** [comment]
Not your fault, this was social engineering attempt. I am millionaire
now! :-)

The GCE is linked to my private account and we should change this to
Ohad's one. Fortunately, AdSense must be explicitly enabled and I
haven't do that for the GCE.

Ohad can you create the same GCE and send me out your GCE ID (or HTML
snippet), I will raise new PR. It's as easy as creating new GCE and
adding this patter to the list of included sites:

```
http://projects.theforeman.org/issues/*
```

## 

Later,
 Lukas #lzap Zapletal

**Pull request merged**
