### PR TITLE
Add commit count output to contributor script

### PR DESCRIPTION
**Pull request by GregSutcliffe**
This adds a `--with-count` option which enables us to see how many commits are in the logs for the time-frame. Obviously, number of commits is not the _best_ metric out there, but I've got to start somewhere :)

I've generated some sample output with just one tagged and one untagged repo:

Existing output is unaltered: http://pastebin.com/Uads9EUA
New output: http://pastebin.com/DwiYQpPz

### CODE REVIEW

**Comment by domcleal** [comment]
Sorry, metric for what?

**Comment by GregSutcliffe** [comment]
Metric on who our most active contributors are (to the repos, anyway). It's just a commit total, so it makes no comment on the complexity of those contributions.

**Comment by domcleal** [comment]
Sure, I was just wondering if this is for the release notes.  Anyway, merged - thanks!

**Comment by GregSutcliffe** [comment]
Only if you want to. I was doing it for my own work/interest, and figured my changes might as well live upstream. Thanks!

**Comment by domcleal** [comment]
That's fine, I'd have questioned it if that's what you were proposing, I just wanted to understand the rationale for the change.

**Pull request merged**
