### PR TITLE
Adding nameserver setting to libvirt provider

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by domcleal** [comment]
Merged, thanks.

**Comment by lzap** [comment]
Well I just learned from Greg that Foreman connects to DNS servers
directly, only if a setting is turned on it goes via system.

Should we mention this here?

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
I thought when you were looking yesterday it wasn't actually doing that?

My suspicion then looking at the code is that dnsmasq doesn't publish an SOA or NS records, so this method of going to authoritative nameservers wasn't actually working.

**Comment by lzap** [comment]
You are absolutely right.

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Pull request closed without merging**
