### PR TITLE
Updated image installation options

### PR DESCRIPTION
**Pull request by lzap**
Starting with this version, I am creating "next" directory which will be the "master" version. Once 12 is released, I will make a copy.

### CODE REVIEW

**Comment by sean797** [comment]
Mind changing `next` to `nightly`? Just to match Foreman and katello docs

**Comment by lzap** [comment]
Sure done.

**Review by sean797 — APPROVED** [review]
ACK

**Comment by mmoll** [comment]
merged, díky @lzap!

**Pull request merged**
