### PR TITLE
Changing use_puppet_default to omit

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by domcleal** [comment]
Would you mind also fixing section 4.2.5 which contains references to "Use Puppet default"? It may need an updated screenshot too, sorry.

**Review by domcleal — APPROVED** [review]

**Review by domcleal — CHANGES_REQUESTED** [review]
Please also update the name given in the "Facts, reporting and parameters" release notes category above.

**Comment by orrabin** [comment]
@domcleal I also changed the screenshots, most of them contained use_puppet_default and the rest I changed because of the difference in css.
I added a new folder for 1.14 because I didn't want to change just part of the 1.11 screenshots. I could change all of the 1.11 parameter schreenshots and then use those that don't contain use_puppet_default here, should I do that or open a separate pr?

**Review by domcleal — APPROVED** [review]

**Comment by domcleal** [comment]
What you've done is great, just replace other screenshots in the 1.14 directory as and when we can. No need to change previous release documentation at this stage.

**Comment by domcleal** [comment]
Merged, thanks @orrabin.

**Pull request merged**
