### PR TITLE
Fix formatting of hammer-cli yaml

### PR DESCRIPTION
**Pull request by dLobatog**
Current format renders well on Github preview but not on Jekyll.

### CODE REVIEW

**Comment by domcleal** [comment]
Hm yeah.  Seems there's some more in section 4.4.  Could you fix that too please?

**Comment by dLobatog** [comment]
@domcleal Thanks for the catch, done.

**Comment by domcleal** [comment]
Sorry, could you also apply that fix to 2.0?  Otherwise :+1:

**Comment by dLobatog** [comment]
Oh right, did that on a rush before lunch. Hope it's ok now.

**Comment by domcleal** [comment]
Thanks @eLobato!

**Pull request merged**
