### PR TITLE
upgraded contributors list on the release notes

### PR DESCRIPTION
**Pull request by karmab**
contributors list retrieved from the autogenerated page https://github.com/theforeman/foreman/blob/develop/Contributors
and added some basic formatting

### CODE REVIEW

**Comment by domcleal** [comment]
The list of contributors here is generated by scripts/commiters.rb and only lists people who contributed between 1.6 and 1.7, so it's meant to be this way.  The contributors list in that repo is for all of history.

**Comment by karmab** [comment]
i guess i m just frustrated i m not in the history list...

**Comment by domcleal** [comment]
Hmm, that's strange, you did commit in that period.

**Comment by domcleal** [comment]
I wonder if I ran 1.5 to 1.6 rather than 1.6 to 1.7.  Let me try updating it...

**Comment by domcleal** [comment]
There we go, sorry about that!

**Pull request closed without merging**
