### PR TITLE
Fix tuning guide table

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by evgeni** [comment]
How about fixing the markdown instead? :)

https://github.com/theforeman/theforeman.org/pull/1634

**Comment by ekohl** [comment]
Closed in favor of #1634

**Comment by ehelms** [comment]
Well, y'all were a bit quick here. I can see the argument for using the
markdown style. I made the switch in part because up above in the file an
html table is used to list supported OSes. So I aimed for consistency.

**Comment by evgeni** [comment]
@ehelms I'd argue the list of supported OSes should be that, a list, not a table?

**Comment by evgeni** [comment]
see https://github.com/theforeman/theforeman.org/pull/1635

**Pull request closed without merging**
