### PR TITLE
Add filecache docs

### PR DESCRIPTION
**Pull request by bochi**
add brief documentaiton on the filecache feature

### CODE REVIEW

**Comment by tbrisker** [comment]
@sbernhard can you please review?

**Comment by sbernhard** [comment]
Thanks @bochi 
I think we should put this to a v 13.1 or even 14.0

**Comment by bochi** [comment]
> Thanks @bochi
> I think we should put this to a v 13.1 or even 14.0

Ok, so - 13.1 or 14? ;-)

**Comment by bochi** [comment]
closing for https://github.com/theforeman/theforeman.org/pull/1653

**Pull request closed without merging**
