### PR TITLE
External Authentication up-to-date.

### PR DESCRIPTION
**Pull request by adelton**
Refactored the original 5.7 SPNEGO authentication authentication to a more generic External Authentication, to cover changes that went to 1.5.

Is there a way to keep the original anchor the http://theforeman.org/manuals/1.5/index.html#5.7SPNEGOauthentication working even with the new 5.7 section name?

### CODE REVIEW

**Comment by stbenjam** [comment]
I think you might have to embed the HTML Anchor in the right place to preserve it...

 <a name="#5.7SPNEGOauthentication"></a>

Maybe someone else knows a better way.

**Comment by stbenjam** [comment]
GitHub swallowed the HTML: `<a name="#5.7SPNEGOauthentication"></a>`

**Comment by adelton** [comment]
> GitHub swallowed the HTML: <a name="#5.7SPNEGOauthentication"></a>

Thanks, added that in 406eed494a7cce76b65f788bb51d42b8c9d9a711.

**Comment by domcleal** [comment]
Thanks @adelton, well-written!

**Comment by adelton** [comment]
Thank you for the merge.

Unfortunately, the original URL http://theforeman.org/manuals/1.5/index.html#5.7SPNEGOauthentication no longer works even if we have

```
<p><a name="#5.7SPNEGOauthentication"></a></p>
```

in the HTML source. I assume it'd because there's some magic working with the anchor. Any recommendation about maintaining the old link?

**Comment by domcleal** [comment]
Sorry, I didn't think to test it.  I've fixed the link, it didn't need the "#".  Although it's not using the tocify Javascript like the menu, so doesn't scroll to precisely the right place, it should be good enough.

**Comment by adelton** [comment]
> it should be good enough

Good enough it is. Thank you!

**Pull request merged**
