### PR TITLE
quickinfo about needed umask setting

### PR DESCRIPTION
**Pull request by mattiascockburn**
Added a quickinfo about the supported umask when using foreman-installer for 1.7/1.8

### CODE REVIEW

**Comment by mmoll** [comment]
Could you please open an issue, which errors are you seeing and which umask was used to get these? I rather want to tackle that in the puppet modules and packages.

**Comment by stbenjam** [comment]
In Katello we have Kafo just set the umask itself: https://github.com/Katello/katello-installer/blob/master/hooks/pre/16-set_umask.rb

Maybe foreman would want to do something similar.  Lots of configuration files end up with incorrect permissions when the umask is set to something restrictive like 027 (especially things that require group ownership).

**Comment by mattiascockburn** [comment]
I will open an issue as soon as i have time to reproduce it. I just heard this from a colleague who was not able to recall the 'real' error he was getting. Closing this PR.

**Comment by mmoll** [comment]
just a quick word, as I didn't have time to try, yet...

If I would be a "customer" which uses a non-default umask (probably for security reasons) and see that a installer of some product is running as root and just setting the umask without even asking, I would feel a bit uneasy.

It's probably much harder for katello to solve with a lot more subsystems to manage, but I think for plain Foreman with the default all-in-one configuration it should be manageable to get there by using more explicit permission and user/group settings in the puppet modules (and maybe changes to packaging, these could get too much to handle, but I'd say let's have a look and try.)

**Comment by stbenjam** [comment]
The problem is we don't control all of the puppet modules we rely on.  puppetlabs-apache, for example.  In Katello, the modules collectively have over 1,000 file resource definitions, and it was something like only 1/5th of them specified full permissions.   Now that was just a quick parsing of the manifests and we're not laying down all those files, but it does give us an idea of how frequently modules are assuming sensible defaults.

For whatever reason, security gurus arbitrarily decide that the defaults supplied by the OS vendor are not strict enough for their purposes.  These 350+ page OS hardening guidelines are 80% hokum. Sorry, OS vendors know what they're doing.  At least in my opinion...

Anyway,  the umask change in Katello is only in the context of the installer, and we log it at the info level.  It goes back to their default when it exists.

We could also just exit and say "Sorry, your umask is ridiculous." I'm fine with either option, but no user's complained about the one I picked in solving that bug so far.

**Comment by mmoll** [comment]
Hm, erroring out would IMHO be indeed better, I think I'll go that way :)

**Comment by stbenjam** [comment]
I don't think changing the umask is that big of a deal. Red Hat's initscripts `functions` even does this so most services are going to start as 022 anyway:

```
# Make sure umask is sane
umask 022
```

**Comment by stbenjam** [comment]
(My point being that probably affects the puppet agent service, at least on EL6)

**Comment by mattiascockburn** [comment]
Well then. If the installer fails with a 'secure' umask being set i will reopen this pull request.

**Comment by mmoll** [comment]
Reopened, but I want to check the situation first and rather add a check in the installer. Adding it for the 1.8 docs might make sense anyway.

**Comment by domcleal** [comment]
I just ran the installer on EL6 under 077 and hit one issue - the Puppet master didn't start as /etc/puppet/environments/common was 0700 and not 0755, I'll file a fix.  Otherwise it seems fine to me in that environment.

**Comment by domcleal** [comment]
Also, note that the umask should only be used in one case IIRC - creation of directories.  For regular files, Puppet copies the source permissions when using file's `source` parameter, or uses a hard-coded default of 0644 when writing from `content`, so this is only a bug affecting some file/directory resources, not those for regular files.

**Comment by mmoll** [comment]
After the recent changes to the puppet module, nightly foreman-installer is working just fine also on Debian/jessie with 0077 umask.

**Comment by domcleal** [comment]
Thanks @mattiasgiese, merging this for now and I'll remove it again once the fixes are released.

**Comment by domcleal** [comment]
You might be interested to know that we're now testing this continuously via http://ci.theforeman.org/view/Status/job/systest_foreman_umask_077/.  Thanks for bringing it to our attention :)

**Pull request merged**
