### PR TITLE
May Community Newsletter

### PR DESCRIPTION
**Pull request by melcorr**
Fixed problems. 
Please review the community newsletter for this month!

### CODE REVIEW

**Comment by lzap** [comment]
Looks good, there is a conflict FYI

**Comment by melcorr** [comment]
> Looks good, there is a conflict FYI

Where?

This is all I see:

This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.

**Comment by lzap** [comment]
Interesting, Reabase and merge fails with:

This branch cannot be rebased due to conflicts

Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch

However Squash and merge does work fine. Anyway, looks good and feel free to merge when you plan to publish it!

**Comment by melcorr** [comment]
Bizarre! Thank you for reviewing.
Also: I have no merge rights on this repo.
Ideally this is published soon.

**Comment by lzap** [comment]
> Bizarre! Thank you for reviewing.

Eh, well it makes sense I have just never stumbled upon it like that on github.

Let me know when to merge, cheers.

**Pull request merged**
