### PR TITLE
Upgrade warning for dropped API endpoints and params

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
I'm adding more the this pr as i progress, please don't merge.

**Comment by tbrisker** [comment]
this now contains all the planned changes, fine to review but wait for them all to be merged before merging this.

**Comment by sharvit** [comment]
The actual drop would be in `2.0`, shouldn't the `1.2` doc suppose to say it is deprecated while the `2.0` doc should point out about the removal?

**Comment by tbrisker** [comment]
> The actual drop would be in `2.0`, shouldn't the `1.2` doc suppose to say it is deprecated while the `2.0` doc should point out about the removal?

this is the 1.2 section of the nightly manual, which will become the 2.0 manual when we branch

**Comment by sharvit** [comment]
> > The actual drop would be in `2.0`, shouldn't the `1.2` doc suppose to say it is deprecated while the `2.0` doc should point out about the removal?
> 
> this is the 1.2 section of the nightly manual, which will become the 2.0 manual when we branch

Thanks for the clarification

**Comment by tbrisker** [comment]
All related PRs have been merged, this is ready to merge

**Comment by mmoll** [comment]
merged, thanks @tbrisker!

**Pull request merged**
