### PR TITLE
Fix Markdown title style

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto roidelapluie@inuits.eu

### CODE REVIEW

**Comment by roidelapluie** [comment]
handbook

**Comment by domcleal** [comment]
Could you also fix the "Notes" section on line 83 in the same way please?

**Comment by roidelapluie** [comment]
@domcleal increased the scope; updated commit message:

While on Github it is allowed to have `##Titles` without space
separation, when converting to HTML a space is needed in `## Titles`.

**Comment by domcleal** [comment]
Thanks @roidelapluie!

**Comment by roidelapluie** [comment]
YAW :)

**Pull request merged**
