### PR TITLE
Fix db instructions

### PR DESCRIPTION
**Pull request by GregSutcliffe**
Saying only 1.0 is confusing, as it means people run the old command for 1.1

### CODE REVIEW

**Comment by domcleal** [comment]
a) could we simply remove this?  The manual's versioned, I think it's safe to lose pre-1.0 instructions now.
b) you'll need to make the same change to 1.2 unfortunately as we've cloned it now
c) it won't merge cleanly

**Comment by domcleal** [comment]
d) bundle exec now shouldn't be used on RPM builds of 1.2 or higher

**Comment by domcleal** [comment]
@GregSutcliffe ping?

**Comment by GregSutcliffe** [comment]
Let me review why I wanted to do this in the first place ;)

**Comment by GregSutcliffe** [comment]
I think I'll close this - let's go down the route of creating that wrapper we were talking about and then producing consistent docs from there....

**Pull request closed without merging**
