### PR TITLE
visual changes to the landing page and a new set of slides for the learn-more page

### PR DESCRIPTION
**Pull request by abenari**

### CODE REVIEW

**Comment by domcleal** [comment]
Very nice, I like that.  Couple of comments:
1. there's a large white space in the footer of the home page on Firefox, below latest news
2. there's no indication of how to browse the presentation (arrow keys only it seems).  If we can get something to click on, that'd be great, else a note to say to use arrows.

**Comment by ohadlevy** [comment]
@domcleal normally when using strut it gives you a visual hint if you dont touch anything after 5 seconds, I would assume it should work here too.

**Comment by domcleal** [comment]
@ohadlevy you're right!

**Comment by lzap** [comment]
This is great.

**Comment by domcleal** [comment]
Thanks @abenari!

**Pull request merged**
