### PR TITLE
Link to the puppetfile-pinner script

### PR DESCRIPTION
**Pull request by ekohl**
I'm not sure where this script should live so this is partially a RFC. It's also not tested with all possible options, but it works for what we have in our current Puppetfile.

### CODE REVIEW

**Comment by ehelms** [comment]
At first pass, this sounds like something that should be run as part of the release process by the Rakefile in the installer?

**Comment by ekohl** [comment]
@ehelms I thought that too. Should we duplicate it in both foreman-installer and katello-installer?

**Comment by ehelms** [comment]
For now I think it has to live in both.

**Comment by ekohl** [comment]
Will update after https://github.com/theforeman/foreman-installer/pull/266 is merged and a similar PR is merged to katello-installer.

**Comment by ekohl** [comment]
The PRs to both installers have now been merged and this can be merged as well.

**Pull request merged**
