### PR TITLE
Fix Foreman top left link, was partially hidden by navbar div

### PR DESCRIPTION
**Pull request by domcleal**
CSS noob here, feel free to admonish me and improve it!  Tested in FF 19.0 only.

### CODE REVIEW

**Comment by ohadlevy** [comment]
@abenari ping ?

**Comment by abenari** [comment]
@domcleal is this in the new top bar? what browser do you use?

**Comment by domcleal** [comment]
@abenari this is the web site, not the app.  It's Firefox 20.0.

**Comment by abenari** [comment]
Couldn't reproduce the issue on my browsers, but the css looks good to me.
:+1:

**Pull request merged**
