### PR TITLE
Adding hidden_value in smart class parameters and variables

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by domcleal** [comment]
This is only in 1.11, so the 1.10 manual can't be changed.  Could you keep hold of this until we start the 1.11 documentation please?

**Comment by orrabin** [comment]
Closing this, I'll reopen when there is a 1.11 manual.

**Comment by domcleal** [comment]
Thanks, I added it to the checklist.  If you're in a documentation writing mood, the 1.10 checklist's still incomplete :)

**Comment by domcleal** [comment]
The 1.11 manual's in place now.

**Comment by orrabin** [comment]
I opened: https://github.com/theforeman/theforeman.org/pull/543 to replace this.

**Pull request closed without merging**
