### PR TITLE
Gh pages who uses foreman

### PR DESCRIPTION
**Pull request by melcorr**
Adding bayerlein networks GmbH

I googled and it seems they don't capitalize these letters!

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Maybe you need to update your branch more often. The history looks very complicated now.

I assume this was communicated with them, otherwise I have Ludwig's contact info.

**Comment by melcorr** [comment]
@ekohl I am adding data entered from the who uses foreman form on the site. 

I googled this problem and found this: 

https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch

I don't know why this occurs.

**Comment by ekohl** [comment]
Generally you want to do:
```bash
git checkout gh-pages
git pull
git checkout gh-pages-who-uses-foreman
git rebase gh-pages
```

Alternative is `git fetch origin && git rebase origin/gh-pages`. Not sure if origin is your remote, but that's the default.

Then force push.

**Comment by melcorr** [comment]
Ewoud, I did exactly that before this. 



> Generally you want to do:
> 
> ```shell
> git checkout gh-pages
> git pull
> git checkout gh-pages-who-uses-foreman
> git rebase gh-pages
> ```
> 
> Alternative is `git fetch origin && git rebase origin/gh-pages`. Not sure if origin is your remote, but that's the default.
> 
> Then force push.

I had pulled from upstream and rebased before creating the branch: 
```shell
mcorr@mcorr theforeman.org]$ git checkout gh-pages
Switched to branch 'gh-pages'
[mcorr@mcorr theforeman.org]$ git fetch origin && git rebase origin/gh-pages
Current branch gh-pages is up to date.
[mcorr@mcorr theforeman.org]$ git checkout gh-pages-who-uses-foreman 
Switched to branch 'gh-pages-who-uses-foreman'
[mcorr@mcorr theforeman.org]$ git rebase gh-pages
Current branch gh-pages-who-uses-foreman is up to date.
```

**Comment by lzap** [comment]
melcorr wants to merge 9 commits into theforeman:gh-pages from **unknown repository**

Uh, have you deleted the repo?

**Comment by lzap** [comment]
Anyway, next time just delete all the branches in your fork and start over by checking out `master` or `gh-pages`. You do not need to delete a fork completely.

**Comment by melcorr** [comment]
I tried everything Lzap, and my branch was up to date. 
@ekohl  suggested many things, I tried every one.

**Comment by ekohl** [comment]
@melcorr I assumed you'd delete your branch for this PR rather than the entire fork. That would probably have been sufficient.

**Comment by melcorr** [comment]
I promise that it wouldn't have @ekohl 
I created the branch for this off a freshly synched fork. 
I don't know how else to get you to believe me so I'll just leave it at this because enough time was wasted.

**Pull request closed without merging**
