### PR TITLE
Fixes #31869 - creates an archive of PDF documents for legacy Katello

### PR DESCRIPTION
**Pull request by jjeffers**
This PR archives legacy releases of Katello documention into PDF files, one per release, from v3.16 to v3.0.
image

A new "legacy/index" displays the archived pdf links.

image

### CODE REVIEW

**Comment by jlsherrill** [comment]
I noticed that the pdfs don't contain any pictures, which makes them look kind of jarring.  Was that intentional ?

**Comment by jjeffers** [comment]
> I noticed that the pdfs don't contain any pictures, which makes them look kind of jarring. Was that intentional ?

No, it wasn't intentional. I can see if the conversion tool left them out of the rendered subparts, or if it was the combining...

**Comment by jjeffers** [comment]
```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File plugins/katello/static/katello_3.1_manual.pdf is 62.18 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.10_manual.pdf is 62.77 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.12_manual.pdf is 74.76 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.13_manual.pdf is 81.20 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.15_manual.pdf is 84.41 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.16_manual.pdf is 89.04 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.2_manual.pdf is 71.91 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.3_manual.pdf is 58.01 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.4_manual.pdf is 63.41 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.5_manual.pdf is 59.38 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.6_manual.pdf is 57.41 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.7_manual.pdf is 61.65 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.9_manual.pdf is 62.78 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.0_manual.pdf is 59.10 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.14_manual.pdf is 84.03 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File plugins/katello/static/katello_3.8_manual.pdf is 62.64 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```
@ekohl We have multiple PDF that are substantially larger than I expected. Perhaps there is a better place to keep these files?

**Comment by jlsherrill** [comment]
We could put them somewhere like here:  https://fedorapeople.org/groups/katello/

I have access and am happy to do that

**Comment by ekohl** [comment]
Tracking these huge files in git is probably not the best way. We've also used https://downloads.theforeman.org/ in the past.

@evgeni do you have any thoughts about the static file hosting?

**Comment by evgeni** [comment]
downloads.tfm sounds like a good place!

**Comment by jlsherrill** [comment]
that sounds like a great place, the katello static storage will probably go away before downloads.theforeman.org

I brought a couple questions up this morning @jjeffers, but to put them here:

1.  any way to remove the links within the pdfs?  
2.  any way to get a bit of the styling back on the pdfs?  They seem very plain

**Comment by lzap** [comment]
If we are setting up a place, we could use it for NG docs which also builds PDFs.

It would be nice if we could set it up in a way that a GH action could upload those PDFs. That would be great!

**Comment by jjeffers** [comment]
> that sounds like a great place, the katello static storage will probably go away before downloads.theforeman.org
> 
> I brought a couple questions up this morning @jjeffers, but to put them here:
> 
> 1. any way to remove the links within the pdfs?
> 2. any way to get a bit of the styling back on the pdfs?  They seem very plain

Updated the conversion tool to disable external links but I am not sure about the styling issues.

**Comment by jlsherrill** [comment]
These look much better!!  @evgeni  would you be able to upload these pdfs to downloads.tfm?  Then james could update this pr to link to them?

**Comment by evgeni** [comment]
Yeah. Drop me a mail with a link where to get them and I'll do Monday/Tuesday.

**Comment by evgeni** [comment]
Screenshot from 2021-03-17 12-41-27
:bowing_woman:

**Comment by evgeni** [comment]
FTR, this should be squashed when merging, so that the history does not contain the PDFs ;)

**Comment by lzap** [comment]
It's been squashed. Git stat looks awesome, probably organizational record? :-)

**Comment by lzap** [comment]
Just a nitpick - we have https://downloads.theforeman.org/katello/documentation-archive/ while we could have some top-level directory like `/docs/archive` so later on we can add Foreman and Katello NG PDFs as well. This way we would probably need to create `/foreman/documentation-archive`.

**Comment by evgeni** [comment]
> Just a nitpick - we have https://downloads.theforeman.org/katello/documentation-archive/ while we could have some top-level directory like `/docs/archive` so later on we can add Foreman and Katello NG PDFs as well. This way we would probably need to create `/foreman/documentation-archive`.

I can move things around, just tell me where to and don't forget to update the PR ;)

**Comment by jjeffers** [comment]
> I can move things around, just tell me where to and don't forget to update the PR ;)

Sounds like '/foreman/documentation-archive/katello' is the preferred layout of these directories?

**Comment by ekohl** [comment]
I think `/foreman` isn't really needed since it's already `downloads.theforeman.org`. The domain should suffice. So `/documentation-archive/$PROJECT` would have my vote.

**Comment by evgeni** [comment]
I have moved things to https://downloads.theforeman.org/documentation-archive/katello/

**Comment by jjeffers** [comment]
@ekohl @evgeni @lzap re-squashed after pointing to the new location

**Comment by lzap** [comment]
I am good, going to give this a spin and merge it.

**Comment by lzap** [comment]
It works. Congratulations to deleting 5 million lines! :-)

**Comment by jjeffers** [comment]
> It works. Congratulations to deleting 5 million lines! :-)

:bow:

**Comment by ekohl** [comment]
For now https://ci.theforeman.org/view/Deploy/job/deploy_web/461/ is still running so nothing has changed yet.

**Pull request merged**
