### PR TITLE
[WIP] Add CentOS 8, RHEL 8 and CentOS Stream 8 as supported platforms

### PR DESCRIPTION
**Pull request by ares**
Also show the same centos 8 installation instructions as for CentOS
Stream 8

### CODE REVIEW

**Comment by evgeni** [comment]
Nack given it's not working on Stream ;)

**Comment by ares** [comment]
Sorry, should have marked it as a draft

**Comment by ekohl** [comment]
You can convert it back to a draft in the top right, in the reviewer section. I did that now.

This is blocked on https://projects.theforeman.org/issues/31527 for now.

**Comment by tbrisker** [comment]
What is the status here?

**Comment by ekohl** [comment]
We added stream as a headline feature for 2.5 so I think we should revisit this.

**Comment by ekohl** [comment]
18484f7f8f0fc43a9b4b612fafbda0d2c3ac09e5 added CentOS/RHEL 8 and f11895ca46646da542137a0a52c2e1dffedc77c1 already added Stream. I'm not sure we need to change the dropdown. If so, we should change it to CentOS Linux/Stream 8 but I'm going to close this PR now. Please open a new one if you think we still need a change.

**Pull request closed without merging**
