### PR TITLE
Netgroups docs

### PR DESCRIPTION
**Pull request by tstrachota**
Copies 1.15 manual into 1.16-develop and adds notes about using netgroups for LDAP auth, which will be released in 1.16.

### CODE REVIEW

**Comment by ares** [comment]
:+1: for netgroups docs, @dLobatog is it a good time for copying the 1.15 manual to 1.16?

**Review by dLobatog — COMMENTED** [review]
@ares Yeah, most definitely, foreman-infra/puppet/modules/web/manifests/init.pp will have to be updated for it to show up.

**Comment by lzap** [comment]
I vote for merging now and putting a warning box about unreleased version the same way as we do for old versions:

https://theforeman.org/manuals/1.14/index.html

**Comment by tstrachota** [comment]
@lzap this is already implemented:
screenshot from 2017-07-20 10-25-16

Plus the version switcher on the main page shows "1.16-develop" so I think it's sufficient warning.
screenshot from 2017-07-20 10-25-06

**Comment by ares** [comment]
Thanks @tstrachota, merging!

**Pull request merged**
