### PR TITLE
Replace Freenode with Libera

### PR DESCRIPTION
**Pull request by melcorr**
I will look around the place in general.

### CODE REVIEW

**Review by ehelms — APPROVED** [review]

**Review by ekohl — COMMENTED** [review]
This is where it can be found.
```console
$ rg -i freenode
plugins/foreman_salt/11.0/index.md
398:If you find a bug, please file it in [Redmine](http://projects.theforeman.org/projects/salt/issues/new).  You can find us on freenode on #theforeman as well.

plugins/foreman_salt/2.1/index.md
345:find us on freenode on #theforeman as well.

plugins/foreman_salt/6.0/index.md
348:find us on freenode on #theforeman as well.

plugins/foreman_salt/13.0/index.md
434:If you find a bug, please file it in [Redmine](https://projects.theforeman.org/projects/salt/issues/new).  You can find us on freenode on #theforeman as well.

plugins/foreman_salt/4.0/index.md
332:find us on freenode on #theforeman as well.

plugins/foreman_salt/5.0/index.md
340:find us on freenode on #theforeman as well.

plugins/foreman_salt/2.0/index.md
293:find us on freenode on #theforeman as well.

plugins/foreman_salt/12.0/index.md
409:If you find a bug, please file it in [Redmine](http://projects.theforeman.org/projects/salt/issues/new).  You can find us on freenode on #theforeman as well.

plugins/foreman_salt/3.0/index.md
321:find us on freenode on #theforeman as well.

plugins/foreman_salt/7.0/index.md
386:find us on freenode on #theforeman as well.

_includes/manuals/1.5/7.2_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.7/7.2_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.18/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.6/7.2_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.14/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/2.1/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.15/7.4_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.17/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/2.2/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.16/7.4_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.22/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/nightly/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/2.4/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.2/6_troubleshooting.md
5:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.1/6_troubleshooting.md
5:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.11/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.21/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.9/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.12/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.23/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.3/6_troubleshooting.md
5:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/2.0/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.13/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.8/7.2_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.20/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.24/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.19/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.4/7.2_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/2.3/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/1.10/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

_includes/manuals/2.5/7.3_getting_help.md
4:We work on the [irc.freenode.net](http://webchat.freenode.net/) servers. You can get general support in #theforeman, while development chat takes place in #theforeman-dev.

privacy.md
104:[Freenode](https://freenode.net), refer to [Freenode's privacy
105:policy][Freenode] for details on how they handle your data. In addition, our
211:[Freenode]: https://freenode.net/policies

handbook.md
227:Generally, if you want to submit significant changes to the code, discuss it first on #theforeman-dev (Freenode) or the Development board on our [forum](https://community.theforeman.org/c/development). If you know who are the usual maintainers for the code you want to change, try to ask them to validate your assumptions, your design, and if they can, ask them to review your code. This will save you a lot of going back and forth with reviewers that do not understand the reasoning behind your pull request.

slides/foreman-intro.html
1231:<li><em>#theforeman</em> on FreeNode</li>

support.md
72:## ![IRC icon](static/images/freenode.png) [IRC live chat](https://kiwiirc.com/client/irc.freenode.net/?#theforeman)
75:* [#theforeman](https://kiwiirc.com/client/irc.freenode.net/?#theforeman) on [irc.freenode.net](http://webchat.freenode.net/)
81:* [#theforeman-dev](https://kiwiirc.com/client/irc.freenode.net/?#theforeman-dev) on [irc.freenode.net](http://webchat.freenode.net/)
108:More information: This [IRC primer](http://irchelp.org/irchelp/ircprimer.html) for new users and the [general IRC guidelines, from freenode](http://freenode.net/channel_guidelines.shtml), are also useful resources.

_posts/2015-02-23-foreman-community-survey-results.md
63:\#theforeman or \#theforeman-dev (IRC channels on Freenode) if there is

_posts/2020-08-31-foreman-community-newsletter-august-2020.md
52:If you're interested in attending this event, add it to your [calendar](https://community.theforeman.org/t/red-hat-product-management-community-update-2/20135?u=mcorr). The YouTube livechat and #theforeman Freenode IRC channel will be monitored for questions. However, this meeting is open to all and if you would like to join the meeting and ask questions yourself, reply to the event and a link will be sent to you!

_posts/2018-10-31-foreman-community-newsletter---october-2018.md
93:* [Freenode #live (2nd-3rd Nov, Bristol)](https://community.theforeman.org/t/freenode-live-conference/11537)
95:Rahul Bajaj will be presenting a talk on Foreman at Freenode #live, so if

_posts/2018-02-28-foreman-community-newsletter---february-2018.md
56:(Freenode/#theforeman).

_posts/2018-01-30-foreman-community-newsletter---january-2018.md
33:(Freenode/#theforeman).

_posts/2017-09-19-linux-image-installs-for-bare-metal.md
43:So I asked in #theforeman IRC channel on Freenode. And then I was told that [Foreman Discovery Image](https://github.com/theforeman/foreman-discovery-image) was designed to be able to be extended. Foreman Discovery Image is the image that boots via PXE and does a inventory of the machine and then waits for a reboot order from Foreman, in order to run a regular(preseed/kickstart) netboot install after discovery.

_posts/2014-10-01-foreman-community-newsletter-september.md
79:\#theforeman in Freenode to ask questions.  

_posts/2019-02-25-introducing-myself.md
27:[Freenode #live](https://freenode.live/), etc. As excinting it is to speak at a conference, 

_posts/2018-04-30-foreman-community-newsletter---april-2018.md
56:(Freenode/#theforeman).

_posts/2017-11-30-foreman-community-newsletter---november-2017.md
66:(Freenode/#theforeman).

_posts/2018-03-31-foreman-community-newsletter---march-2018.md
38:(Freenode/#theforeman).

_posts/2018-05-18-contributing-to-installer-puppet-modules.md
67:If the command was not successful, please reach out to the [foreman-dev discourse list](https://community.theforeman.org/c/development) (preferred), or #theforeman-dev on freenode. We love having new contributors; someone will help you. It's possible that you did everything correctly and there is a bug in forklift, so don't be afraid to reach out for assistance.

_posts/2017-09-26-foreman-community-newsletter---september-2017.md
67:(Freenode/#theforeman).

_posts/2017-12-28-foreman-community-newsletter---december-2017.md
40:(Freenode/#theforeman).

_posts/2017-07-31-foreman-community-newsletter---july-2017.md
57:(Freenode/#theforeman).

_posts/2017-08-31-foreman-community-newsletter---august-2017.md
61:(Freenode/#theforeman).

_posts/2017-10-31-foreman-community-newsletter---october-2017.md
56:Freenode, so you can freely use IRC or Matrix to chat with us. I've personally
88:(Freenode/#theforeman).

mentoring.md
21:  * \#theforeman on Freenode for generally getting to know Foreman and asking user questions
22:  * \#theforeman-dev on Freenode for development/mentoring questions. Don't be shy; tell us you're interested in one of our open mentoring projects
120:to ask in #theforeman-dev on Freenode.
```

**Comment by melcorr** [comment]
@ekohl  do you think I need to change old blog posts?

**Comment by ekohl** [comment]
I think it would be good to do so. Let's get rid of all public references.

**Comment by melcorr** [comment]
I'll do that then!

**Comment by melcorr** [comment]
I'm bleary eyed so will check this tomorrow. Could have done some dodgy sedding
I removed specific web chats as things are unstable and they are listed on libera.chat so people can make their own choices.

**Review by ekohl — CHANGES_REQUESTED** [review]
Please https links for libera.chat. You can easily replace it with `sed -i 's|http://libera.chat|https://libera.chat|g' $(git show --name-only --pretty="format:")`

**Comment by melcorr** [comment]
Anything else?

**Review by ekohl — APPROVED** [review]
The only thing I'd note is that sometimes it's libera.chat (as human readable version) and sometimes Libera.Chat. I'm ok with merging this either way. Feel free to merge it yourself if you don't want to address it.

**Comment by melcorr** [comment]
> The only thing I'd note is that sometimes it's libera.chat (as human readable version) and sometimes Libera.Chat. I'm ok with merging this either way. Feel free to merge it yourself if you don't want to address it.

I did that on purpose @ekohl but I've forgotten the reason why in the last week. :-/

**Comment by melcorr** [comment]
Got rid of the upper-case instances.

**Pull request merged**
