### PR TITLE
Remove EL6 installation instructions

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@domcleal EL6 PR (https://github.com/theforeman/foreman-packaging/pull/1344) according to @ehelms is nearly done. hence, IMHO we are keeping EL6 support for one more release.

**Comment by domcleal** [comment]
We're not, 1.13.0-RC1 doesn't contain EL6 packages, it missed it by a _long_ way. This is correct.

**Comment by ohadlevy** [comment]
I respectively disagree.

**Comment by domcleal** [comment]
Like with #675, I'd prefer that the docs are accurate, whether or not you personally agree with the change. If the situation changes again then the docs can be updated trivially.

Can I reopen this PR and ask please for a re-review?

**Pull request closed without merging**
