### PR TITLE
Remove clearing sessions command after upgrade

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ekohl** [comment]
Why exactly is this no longer needed?

**Comment by xprazak2** [comment]
The command to clear sessions is no longer available in Rails 5.x
https://community.theforeman.org/t/documentation-update-needed/10868

**Comment by ekohl** [comment]
I think clearing the sessions is still a good thing. In https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html they mention `db:sessions:clear` as a replacement. Should we use that instead?

**Comment by xprazak2** [comment]
Yes, we probably should. Updated.

**Review by ekohl — APPROVED** [review]

**Comment by mmoll** [comment]
merged, díky @xprazak2!

**Pull request merged**
