### PR TITLE
add june community newsletter

### PR DESCRIPTION
**Pull request by melcorr**
I've written about the 2.1.0 release as if it was released. 
I might need to add more details.

### CODE REVIEW

**Comment by rabajaj0509** [comment]
Hello @melcorr, would you like to add a talk i did: https://bit.ly/2ZBo29v 
It has a complete overview of the Single Sign On feature we implemented in the Foreman Project. There is an demonstration too at the end of the talk that shows how we can authenticate using Keycloak in Foreman.

Here is the abstract to the talk: https://stackconf.eu/talks/securing-infrastructure-with-keycloak/

**Comment by melcorr** [comment]
> Hello @melcorr, would you like to add a talk i did: https://bit.ly/2ZBo29v
> It has a complete overview of the Single Sign On feature we implemented in the Foreman Project. There is an demonstration too at the end of the talk that shows how we can authenticate using Keycloak in Foreman.
> 
> Here is the abstract to the talk: https://stackconf.eu/talks/securing-infrastructure-with-keycloak/

Hi @rabajaj0509 - I can add a reference to this but what I would really like is if you could write a summary, link to the video, and write out the different steps from the demo at the end and post it in a blog form so that people searching online might find the steps and come to the Foreman community. What do you think ?

**Comment by rabajaj0509** [comment]
Community member [@rabajaj](https://community.theforeman.org/u/rabajaj) gave a complete overview of the Single Sign On feature in Foreman at [Stackconf](https://stackconf.eu/) in June. Check out the [full presentation](https://stackconf.eu/talks/securing-infrastructure-with-keycloak/).

With the help of OpenID Connect, Foreman can provide Single Sign On(SSO) functionality. In this talk, we will understand how one can leverage Keycloak, an OpenID provider, to perform Sign Sign On using the JSON Web Tokens(JWT).
[JSON Web Tokens] (https://youtu.be/1dRMNzYHdDs?list=PLeoxx10paaAnznPuC8HQlpXi23pOxzyfg&t=220)
[OAuth 2.0] (https://youtu.be/1dRMNzYHdDs?list=PLeoxx10paaAnznPuC8HQlpXi23pOxzyfg&t=571)
[OpenID Connect] (https://youtu.be/1dRMNzYHdDs?list=PLeoxx10paaAnznPuC8HQlpXi23pOxzyfg&t=771)
[OAuth 2.0 workflows] (https://youtu.be/1dRMNzYHdDs?list=PLeoxx10paaAnznPuC8HQlpXi23pOxzyfg&t=955)
[Keycloak as an OpenID provider] (https://youtu.be/1dRMNzYHdDs?list=PLeoxx10paaAnznPuC8HQlpXi23pOxzyfg&t=1166)
[Single Sign On with Foreman] (https://youtu.be/1dRMNzYHdDs?list=PLeoxx10paaAnznPuC8HQlpXi23pOxzyfg&t=1976)  

@melcorr feel free to rephrase the sentences :) Don't forget to remove the spaces between `[] ()`. 
nit: there is a small typo in the `ca omplete` there. Also, would be better to have that section called `Community Demos and conferences` for this month?

**Comment by melcorr** [comment]
Hi @rabajaj0509  - I meant that you would please submit this as a separate blog post. I am happy to add info to the newsletter but if someone is searching for this info at a later date, they won't think to check the newsletter.

**Pull request merged**
