### PR TITLE
blog: 2017 survey analysis

### PR DESCRIPTION
**Pull request by GregSutcliffe**
Okay, this is huge. Quick comments:

* First draft, changes and more conclusions welcome
* I've used HTML tables instead of the bar graphs since they didn't work so well last year. Bar graphs can be clicked through to see if you want
* Probably some links that need adding, I'll do a second pass tomorrow but shout if if you see it first
* Probably hundreds of typos

@witlessbird @jlsherrill @bmbouter care to check your questions over and see if you want to add anything?

### CODE REVIEW

**Comment by dmitri-d** [comment]
in static/images/blog_images/2017-03-29-2017-foreman-survey-analysis/basic/how_long_using.png: labels answer a question different from the title of the image?

**Comment by GregSutcliffe** [comment]
Oh one other option- if it's too big I can try and do it as multiple pages. Opinions welcome.

**Comment by GregSutcliffe** [comment]
@witlessbird good catch, the labels were from the previous year where I think we phrased it as "When did you start using Foreman?". It doesn't affect the data, but I can add a clarification if you like.

**Comment by dmitri-d** [comment]
> I can add a clarification if you like.

I'm ok with it if you are. Just caught my attention.

**Comment by dmitri-d** [comment]
That's the only issue I can see, lgtm.

**Comment by GregSutcliffe** [comment]
Fixed a bunch of typos and grammatical errors, and added some useful links in good places. If there's no further comments, can someone push it? I'd like to mention it in the newsletter I'm just writing :)

**Comment by mmoll** [comment]
merged, thanks @GregSutcliffe!

**Pull request merged**
