### PR TITLE
Katello 3.12 GA

### PR DESCRIPTION
**Pull request by chris1984**
@jturel when GA is ready to go

### CODE REVIEW

**Comment by jturel** [comment]
Looks good, needs some extras:

```
[jturel@strangeways katello]$ git grep 'latest: '
2.4/installation/2.0-transition.md:latest: '3.11'
2.4/installation/index.md:latest: '3.11'
3.0/installation/index.md:latest: '3.11'
3.1/installation/index.md:latest: '3.11'
3.10/installation/index.md:latest: '3.11'
3.11/installation/index.md:latest: '3.11'
3.12/installation/index.md:latest: '3.12'
3.2/installation/index.md:latest: '3.11'
3.3/installation/index.md:latest: '3.11'
3.4/installation/index.md:latest: '3.11'
3.5/installation/index.md:latest: '3.11'
3.6/installation/index.md:latest: '3.11'
3.7/installation/index.md:latest: '3.11'
3.8/installation/index.md:latest: '3.11'
3.9/installation/index.md:latest: '3.11'
nightly/installation/index.md:latest: nightly
```
The "3.11" should be "3.12"

**Comment by chris1984** [comment]
@jturel thanks for catching that, updated

**Review by jturel — APPROVED** [review]
ACK pending 3.12 GA - Thanks Chris!

**Comment by chris1984** [comment]
@ehelms this is ready to go, testing looks good

**Review by ehelms — APPROVED** [review]

**Pull request merged**
