### PR TITLE
Rewrite the Salt plugin page to include all content

### PR DESCRIPTION
**Pull request by ekohl**
It's suprising to have the 14.0 documentation have the general information. This makes the landing page contain all the information and redirects the Salt 14.0 manual to the index page.

It also fixes some links to reflect some moves.

### CODE REVIEW

**Comment by ekohl** [comment]
@maximiliankolb mind having a look at this?

**Review by maximiliankolb — APPROVED** [review]
Diff LGTM. Is there any way to view a preview of this change?

**Comment by ekohl** [comment]
> Diff LGTM. Is there any way to view a preview of this change?

https://github.com/theforeman/theforeman.org?tab=readme-ov-file#locally

**Comment by maximiliankolb** [comment]
LGTM! (assuming the missing icons are a local glitch on my end)

image

**Review by maximiliankolb — APPROVED** [review]

**Pull request merged**
