### PR TITLE
blog: Add action plan on review culture

### PR DESCRIPTION
**Pull request by GregSutcliffe**
Mostly an opinion piece, but a grammar/spelling review would be good. Bonus points if anyone is willing to check my plan is actually what we discussed the dev thread :)

### CODE REVIEW

**Comment by dmitri-d** [comment]
lgtm.

**Comment by GregSutcliffe** [comment]
@dLobatog, would you mind? :)

**Comment by dLobatog** [comment]
Merged as 55fb3573bfb9fd097bb1ff65a282cfe6b516711d, thanks @GregSutcliffe!

**Comment by dLobatog** [comment]
Kinda wary of merging plans (been burned w/ similar stuff before, Kubernetes & foreman-docker for example in this project), but if it's going to happen it's a great intro. Thanks again!

**Comment by GregSutcliffe** [comment]
Thanks @dLobatog - I sort of agree with you, but the purpose of publishing this is to _force_ commitment to implementing this. You can view it as a self-fulfilling prophecy :)

**Pull request closed without merging**
