### PR TITLE
Foreman version for Katello 3.5 is 1.16

### PR DESCRIPTION
**Pull request by coffmant**

### CODE REVIEW

**Review by akofink — APPROVED** [review]
ACK from me

**Comment by GregSutcliffe** [comment]
Ty!

**Comment by ekohl** [comment]
Given we also had https://github.com/theforeman/theforeman.org/pull/982 - is this something we should put in our release process somewhere?

**Comment by akofink** [comment]
I agree a list of files to change would be nice. The current process is basically to grep for 3.4 (and 1.15, which I missed).

**Pull request merged**
