### PR TITLE
Added SSH BMC provider

### PR DESCRIPTION
**Pull request by lzap**
SSIA

### CODE REVIEW

**Comment by domcleal** [comment]
This isn't an option in 1.13, it was added in 1.14.0 (see http://projects.theforeman.org/issues/10250). Add it to #708?

**Comment by lzap** [comment]
Indeed, sorry about that. Adding there.

**Comment by domcleal** [comment]
Please reopen against the 1.14 manual.

**Comment by dLobatog** [comment]
https://github.com/theforeman/theforeman.org/pull/770 to save some time

**Pull request closed without merging**
