### PR TITLE
Add deprecation and upgrade warnings for Proxy DNS

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]

**Comment by tbrisker** [comment]
Oops, looks like i just merged similar change @lzap did in https://github.com/theforeman/theforeman.org/pull/1392

**Comment by ekohl** [comment]
I wasn't aware of his PR. I do think the removed part belongs in upgrade warnings rather than deprecations. I'll rebase this.

**Comment by tbrisker** [comment]
> I wasn't aware of his PR. 

Looks like that was mutual :)

**Comment by ekohl** [comment]
Updated

**Review by chris1984 — APPROVED** [review]
LGTM

**Review by tbrisker — APPROVED** [review]

**Comment by tbrisker** [comment]
Thanks @ekohl

**Pull request merged**
