### PR TITLE
Loading rails console, foreman-rake

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
:+1:

**Comment by domcleal** [comment]
psst, click the merge button :wink:

**Comment by GregSutcliffe** [comment]
I dislike the github merge button, it generates merge commits which are ugly. Thus if I'm not in a situation to go to my filesystem, pull the change and push it back, you'll only get a :+1: from me :P

**Comment by GregSutcliffe** [comment]
Thanks @domcleal

**Pull request merged**
