### PR TITLE
Add doc for template export

### PR DESCRIPTION
**Pull request by xprazak2**
Docs for [template export API](https://github.com/theforeman/foreman_templates/pull/51)

### CODE REVIEW

**Comment by ares** [comment]
Thanks, looks good to me, will merge after the PR in foreman_templates gets in.

**Comment by ares** [comment]
@xprazak2 would you mind rebasing this?

**Comment by xprazak2** [comment]
I rebased.

**Comment by ares** [comment]
Thanks @xprazak2, merging.

**Pull request merged**
