### PR TITLE
blog: add post on Discourse migration

### PR DESCRIPTION
**Pull request by GregSutcliffe**
Basically the same text as the mail I just sent to the mailing lists - just for those who might only be on the rss feed, and for a convenient thing to link to elsewhere. I'll tweet a link to this once it's published.

Will do another PR for adding Discourse links to the website itself.

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Does anyone think I should also put this in the frontpage alertbox?

**Comment by ares** [comment]
> Does anyone think I should also put this in the frontpage alertbox?

that can't hurt

**Comment by GregSutcliffe** [comment]
@ares done, sorry for the delay. Updated the date on the post.

**Comment by ares** [comment]
LGTM, the alert is on the bottom and not too visible but if that's what you had in mind, I guess it can be merged

**Comment by GregSutcliffe** [comment]
@ares it appears at the top of the frontpage on my local copy. I'll go ahead and merge since we're into the weekend,will send another PR if it doesn#'t work live FSR. ty!

**Pull request merged**
