### PR TITLE
Fixes #1087 - Add sudo to quickstart commands

### LINKED ISSUE #1087: Small Syntax error on Installation Quickstart
On the Quickstart link

https://www.theforeman.org/manuals/1.17/quickstart_guide.html

Installation Options for:

- Debian 9 (Stretch)
- Ubuntu 16.04 (Xenial)

Enable the Foreman Repo, last line (4)

`wget -q https://deb.theforeman.org/pubkey.gpg -O- | apt-key add -`

**Only works if the second command on the pipe is issued with sudo**

`wget -q https://deb.theforeman.org/pubkey.gpg -O- | sudo apt-key add -`

### PR DESCRIPTION
**Pull request by GregSutcliffe**
I *think* I got everything in the quickstart....

### CODE REVIEW

**Review by dLobatog — CHANGES_REQUESTED** [review]
@GregSutcliffe Thanks, looks good to me. The issue number seems to point to a different problem, typo?

**Comment by GregSutcliffe** [comment]
@dLobatog ugh, forgot to create a redmine issue, just a ref to GH. Let me remove it, it's not a hard requirement for this repo...

**Comment by ekohl** [comment]
@GregSutcliffe could you use Fixes GH-1087 instead of `#`?

**Comment by GregSutcliffe** [comment]
@ekohl @dLobatog done

**Review by dLobatog — APPROVED** [review]

**Comment by dLobatog** [comment]
Thanks @GregSutcliffe !

**Pull request merged**
