### PR TITLE
Addressing CVEs with Foreman and katello

### PR DESCRIPTION
**Pull request by dLobatog**
In light of the recently released CVEs DROWN and GHOST, I decided to
write a blogpost explaining how to patch your systems with Foreman
and Katello.

I'd appreciate comments if anything is unclear, context is missing, etc.. 

Thanks for reviewing!

### CODE REVIEW

**Comment by ohadlevy** [comment]
@dLobatog :100: @ehelms, @bbuckingham or @jlsherrill can you have a look please? thanks!

**Comment by ehelms** [comment]
Looks great, three things worth considering:

 1) swap references of system to host throughout
 2) mentioning that the errata application process "patches" the content views generating a minor version
 3) consider mentioning that you can individually target CVEs; as well you can use the filtering for security, available and installable to identify all CVEs that may apply

**Comment by dLobatog** [comment]
@ehelms thanks for taking a look:

1) Done
2) I don't have any content host in a view that doesn't have the latest errata - how can I create a content view that does not contain the errata I want to apply in this blogpost?
3) I think I show first the 'target specific CVEs' approach - then the 'apply all errata' approach in the blogpost. It's true I don't mention anything about installable vs applicable etc.. not sure if it's the place for it or if I should just link to documentation?

**Comment by jlsherrill** [comment]
@dLobatog:

2) You can simply create an 'errata by id' filter that 'excludes' a particular errata.  Then republish with that filter and viola the content view version published should not contain that errata.
3) I would just link to the docs for that specifically, its spelled out pretty well

looks good :+1:

**Comment by bbuckingham** [comment]
@dLobatog, Looks very good!  Thanks!

**Comment by mmoll** [comment]
merged, gracias @dLobatog!

**Pull request closed without merging**
