### PR TITLE
Added incremental backup example

### PR DESCRIPTION
**Pull request by lzap**
SSIA

### CODE REVIEW

**Comment by mmoll** [comment]
@jlsherrill @ehelms ☝️

**Comment by lzap** [comment]
Fixed problem when locale was not set to Czech - fyi we start a week with Monday :-) Credit goes to https://bugzilla.redhat.com/show_bug.cgi?id=1446070 folks.

**Comment by dLobatog** [comment]
Thanks @lzap , this looks good (I need to try the script yet). This has been on 3.2, 3.3 and 3.4 already, do you mind copying that over to those versions too? I'm not sure about 3.2 but 3.3 and 3.4 are still supported AFAIK.

**Comment by lzap** [comment]
Done, already tested that in Madrid! :-)

**Comment by dLobatog** [comment]
Thanks @lzap !

**Pull request merged**
